# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Llama3.2 1B Instruct model
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download meta-llama/Llama-3.2-1B-Instruct --output-dir /tmp/Llama-3.2-1B-Instruct --ignore-patterns "original/consolidated.00.pth"
#
# To launch on 4 devices, run the following command from root:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2/1B_full
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nproc_per_node 4 full_finetune_distributed --config llama3_2/1B_full checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# Single device full finetuning requires more memory optimizations. It's
# best to use 1B_full_single_device.yaml for those cases

##################################################
########## START CUSTOM KEYS

optimizer_name: adamw
dataset_split: train_1M

batch_size: 2
gradient_accumulation_steps: 32

learning_rate: 1e-5
weight_decay: 0

# Training
seed: 42
shuffle: True
epochs: 1
max_steps_per_epoch: null

# Environment
device: cuda
dtype: bf16

# Memory management
enable_activation_checkpointing: False  # True reduces memory
enable_activation_offloading: False  # True reduces memory
clip_grad_norm: 1
compile: False  # torch.compile the model + loss, True increases speed + decreases memory
optimizer_in_bwd: False  # True saves memory. Requires gradient_accumulation_steps=1

extra: bs=${batch_size}_gas=${gradient_accumulation_steps}_cg=${clip_grad_norm}_split=${dataset_split} # used as a shortcut in the config
root_dir: /data/imodoranu/results/
output_dir: ${root_dir}/${wandb.project}/${wandb.group}/${wandb.job_type}/${wandb.name}

optimizer:
    adamw:
        _component_: torch.optim.AdamW
        lr: ${learning_rate}
        weight_decay: ${weight_decay}
        betas:
            - 0.9
            - 0.999
        eps: 1e-8
        fused: True
    micro_adam_cuda_fsdp2:
        _component_: memory_efficient_optimizers.MicroAdamCUDAFSDP2
        lr: ${learning_rate}
        weight_decay: ${weight_decay}
        betas:
            - 0.9
            - 0.999
        eps: 1e-8
        num_grads: 10
        density: 0.01
        quant_block_size: 64
        decay_all_weights: 1
    frugal_micro_adam_fsdp2:
        _component_: memory_efficient_optimizers.FrugalMicroAdamTorchFSDP2
        lr: ${learning_rate}
        weight_decay: ${weight_decay}
        betas:
            - 0.9
            - 0.999
        eps: 1e-8
        num_grads: 10
        density: 0.01
        use_sign_sgd: 0
        normalization: none
    custom_ema_adamw:
        _component_: memory_efficient_optimizers.CustomEmaAdamW
        lr: ${learning_rate}
        weight_decay: ${weight_decay}
        betas:
            - 0.9
            - 0.999
        eps: 1e-8
        ema_schedule: delayed
        ema_decay: 10
        ema_alpha: 0.001

wandb:
    project: ionut_torchtune_llama3.2-1B_full_ft_multi_gpu
    entity: ionutmodo
    job_type: lr=${learning_rate}
    name: seed=${seed}
    group: ${wandb.groups.${optimizer_name}}
    groups:
        adamw: adamw_${extra}
        micro_adam_cuda_fsdp2: micro-adam_${extra}_ng=${optimizer.micro_adam_cuda_fsdp2.num_grads}_k=${optimizer.micro_adam_cuda_fsdp2.density}_qbs=${optimizer.micro_adam_cuda_fsdp2.quant_block_size}_daw=${optimizer.micro_adam_cuda_fsdp2.decay_all_weights}
        frugal_micro_adam_fsdp2: frugal-micro-adam-sgd=${optimizer.frugal_micro_adam_fsdp2.use_sign_sgd}_${extra}_ng=${optimizer.frugal_micro_adam_fsdp2.num_grads}_k=${optimizer.frugal_micro_adam_fsdp2.density}_norm=${optimizer.frugal_micro_adam_fsdp2.normalization}
        custom_ema_adamw: custom-ema-adamw_${extra}_sched=${optimizer.custom_ema_adamw.ema_schedule}-${optimizer.custom_ema_adamw.ema_decay}_a=${optimizer.custom_ema_adamw.ema_alpha}

# Logging
metric_logger:
    _component_: torchtune.training.metric_logging.WandBLogger
    project: ${wandb.project}
    entity: ionutmodo
    group: ${wandb.group}
    job_type: ${wandb.job_type}
    name: ${wandb.name}
    log_dir: ${output_dir}/logs
log_every_n_steps: 10
log_peak_memory_stats: True
log_level: INFO  # DEBUG, WARN, etc.
########## END CUSTOM KEYS
##################################################

#lr_scheduler:
#    _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
#    num_warmup_steps: 6250 # 10% of training

# Dataset and Sampler
dataset:
    _component_: torchtune.datasets.open_math_instruct_2_dataset
    packed: False  # True increases speed
    split: ${dataset_split}
    column_map:
        input: problem
        output: generated_solution

# Tokenizer
tokenizer:
    _component_: torchtune.models.llama3.llama3_tokenizer
    path: /data/imodoranu/huggingface/Llama-3.2-1B-Instruct/original/tokenizer.model
    max_seq_len: null


run_val_every_n_steps: 100  # Change to an integer to enable validation every N steps
dataset_val:
    _component_: ${dataset._component_}
    split: train_2M[:1%]
    column_map:
        input: problem
        output: generated_solution
batch_size_val: 1

model:
    _component_: torchtune.models.llama3_2.llama3_2_1b

checkpointer:
    _component_: torchtune.training.FullModelHFCheckpointer
    checkpoint_dir: /data/imodoranu/huggingface/Llama-3.2-1B-Instruct/
    checkpoint_files: [
        model.safetensors
    ]
    recipe_checkpoint: null
    output_dir: ${output_dir}
    model_type: LLAMA3_2
resume_from_checkpoint: False

loss:
    _component_: torchtune.modules.loss.LinearCrossEntropyLoss

# Profiler (disabled)
profiler:
    _component_: torchtune.training.setup_torch_profiler
    enabled: False

    #Output directory of trace artifacts
    output_dir: ${output_dir}/profiling_outputs

    #`torch.profiler.ProfilerActivity` types to trace
    cpu: True
    cuda: True

    #trace options passed to `torch.profiler.profile`
    profile_memory: False
    with_stack: False
    record_shapes: True
    with_flops: False

    # `torch.profiler.schedule` options:
    # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
    wait_steps: 5
    warmup_steps: 3
    active_steps: 2
    num_cycles: 1
